### PR TITLE
Change 404 messages for a not found blog entry

### PR DESCRIPTION
**Pull request by ChristianGaertner**
Changed "page not found" to "post not found".
I think this a bit more specific and easier to understand.
Cheers.

### CODE REVIEW

**Comment by ericlbarnes** [comment]
I think we should instead throw this with a theme 404.blade.php file. That way it will allow complete customization and be better long term.

**Comment by ChristianGaertner** [comment]
Agree with that. I think my latest commit in this pull request should cover this.

Cheers

**Comment by ericlbarnes** [comment]
It appears I already have an app::missing - 
https://github.com/ericbarnes/wardrobe/blob/master/app/filters.php#L25

I am testing this locally and it is throwing the correct view even when the post isn't found. Is that not the results you are getting?

**Comment by ChristianGaertner** [comment]
Was just putting my together and didn' t really check how it behaved before...

Just tested it with the master branch (without my commits) and it works as well.
Sorry for the trouble :/ Just saw previous issues and the source and thought to improve the messages (my first commit)...

Cheers.

**Comment by ericlbarnes** [comment]
Cool no worries. Thanks for the help!

**Pull request closed without merging**
