### PR TITLE
Improved Installation Workflow

### PR DESCRIPTION
**Pull request by adamgoose**
- Added landing at / to prompt an install
- Added database credentials to installation
- Minimized errors when uninstalled

Signed-off-by: Adam Engebretson adam@enge.me

### CODE REVIEW

**Comment by ericlbarnes** [comment]
Brilliant! No time to test currently but will try and get to this at some point this week.

**Comment by ericlbarnes** [comment]
Just pulled this down and I like it. However if we go this route I think we should attempt to account for some of the other types. At least mysql, postgres, and sqlite.

**Comment by adamgoose** [comment]
Sure thing - I have just never used any of the others. :/

**Comment by ericlbarnes** [comment]
Postgres should really be the same. You just set the config/db file differently. I believe sqlite just uses a file.

**Comment by adamgoose** [comment]
Alrighty. I'll tackle that today!

**Comment by ericlbarnes** [comment]
sweet! Just an fyi I made some changes in the InstallController to fix #33 at lunch. So you may run into a conflict.

**Comment by adamgoose** [comment]
I'll probably pull a fresh copy and start from scratch. Wasn't too difficult. :)

**Pull request closed without merging**
